### ISSUE TITLE
Remove "Please provide your email for confirmation" popup

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#19]
Currently after pressing the "send reset link" button and then clicking the "sign in to fileinbox" link from the email, there's a popup on the login page that asks to confirm the email address:

<img width="640" alt=" 2024-01-02 at 2 51 43 PM Large" src="https://github.com/Taoula/firebaseui-react/assets/179361/4a5210fb-0f4d-4fb6-858c-e3ea4a649be5">

The user's email is already in the query parameters so this popup shouldn't be necessary. Please remove it.

**Comment by Taoula** [comment]
<img width="872" alt="Screenshot 2024-01-05 at 1 50 15 PM" src="https://github.com/Taoula/firebaseui-react/assets/26856988/beae6b9d-8ddb-43ca-a122-c2d20c8dae83">
Looks like this was built in to the useFirebase hook on FileInbox as a fallback for when no email is provided. I changed the variable name to `email` instead of `firebase:email`, and pushed to my branch on FileInbox.

**Comment by christiangenco** [comment]
Hang on, what? How was `checkEmailLink` from `useFirebase` getting called? FirebaseUI shouldn't know about the useFirebase hook.
